import skgenome.io.fasta


def test_read(fasta):
    x = skgenome.io.fasta.read(fasta)

    y = [
        (
            "MDSKGSSQKGSRLLLLLVVSNLLLCQGVVSTPVCPNGPGNCQVSLRDLFDRAVMVSHYIHDLSSE"
            "MFNEFDKRYAQGKGFITMALNSCHTSSLPTPEDKEQAQQTHHEVLMSLILGLLRSWNDPLYHLVT"
            "EVRGMKGAPDAILSRAIEIEEENKRLLEGMEMIFGQVIPGAKETEPYPVWSGLPSLQTKDEDARY"
            "SAFYNLLHCLRRDSSKIDTYLKLLNCRIIYNNNC*",
            None,
        ),
        (
            "ADQLTEEQIAEFKEAFSLFDKDGDGTITTKELGTVMRSLGQNPTEAELQDMINEVDADGNGTIDF"
            "PEFLTMMARKMKDTDSEEEIREAFRVFDKDGNGYISAAELRHVMTNLGEKLTDEEVDEMIREADI"
            "DGDGQVNYEEFVQMMTAK*",
            "MCHU - Calmodulin - Human, rabbit, bovine, rat, and chicken",
        ),
        (
            "LCLYTHIGRNIYYGSYLYSETWNTGIMLLLITMATAFMGYVLPWGQMSFWGATVITNLFSAIPYI"
            "GTNLVEWIWGGFSVDKATLNRFFAFHFILPFTMVALAGVHLTFLHETGSNNPLGLTSDSDKIPFH"
            "PYYTIKDFLGLLILILLLLLLALLSPDMLGDPDNHMPADPLNTPLHIKPEWYFLFAYAILRSVPN"
            "KLGGVLALFLSIVILGLMPFLHTSKHRSMMLRPLSQALFWTLTMDLLTLTWIGSQPVEYPYTIIG"
            "QMASILYFSIILAFLPIAGXIENY",
            "gi|5524211|gb|AAD44166.1| cytochrome b [Elephas maximus maximus]",
        ),
    ]

    assert x == y
